// <auto-generated />
using System;
using Core.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MvcApp.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("COURSES", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("COURSE_ID");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("GROUPS", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STUDENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GROUP_ID");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("STUDENTS", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Course", b =>
                {
                    b.OwnsOne("Core.ValueObjects.DataCourse", "DataCourse", b1 =>
                        {
                            b1.Property<int>("CourseId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DESCRIPTION");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NAME");

                            b1.HasKey("CourseId");

                            b1.ToTable("COURSES");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("DataCourse");
                });

            modelBuilder.Entity("Core.Entities.Group", b =>
                {
                    b.HasOne("Core.Entities.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId");

                    b.OwnsOne("Core.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("GroupId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("NAME");

                            b1.HasKey("GroupId");

                            b1.ToTable("GROUPS");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.Navigation("Course");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Core.Entities.Student", b =>
                {
                    b.HasOne("Core.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.OwnsOne("Core.ValueObjects.StudentName", "StudentName", b1 =>
                        {
                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.HasKey("StudentId");

                            b1.ToTable("STUDENTS");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");

                            b1.OwnsOne("Core.ValueObjects.Name", "FirstName", b2 =>
                                {
                                    b2.Property<int>("StudentNameStudentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("FIRST_NAME");

                                    b2.HasKey("StudentNameStudentId");

                                    b2.ToTable("STUDENTS");

                                    b2.WithOwner()
                                        .HasForeignKey("StudentNameStudentId");
                                });

                            b1.OwnsOne("Core.ValueObjects.Name", "LastName", b2 =>
                                {
                                    b2.Property<int>("StudentNameStudentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("LAST_NAME");

                                    b2.HasKey("StudentNameStudentId");

                                    b2.ToTable("STUDENTS");

                                    b2.WithOwner()
                                        .HasForeignKey("StudentNameStudentId");
                                });

                            b1.Navigation("FirstName")
                                .IsRequired();

                            b1.Navigation("LastName")
                                .IsRequired();
                        });

                    b.Navigation("Group");

                    b.Navigation("StudentName")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Core.Entities.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
